# Generated by Django 3.1.1 on 2020-09-29 15:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('total_chapters', models.PositiveIntegerField(default=0)),
                ('chapters_read', models.PositiveIntegerField(default=0)),
                ('started_on', models.DateField()),
                ('completed_on', models.DateField()),
                ('my_review', ckeditor.fields.RichTextField()),
                ('genre', models.CharField(choices=[('self help', 'self help'), ('crime', 'crime'), ('fiction', 'fiction'), ('non fiction', 'non fiction'), ('other', 'other')], default='other', max_length=255)),
                ('cover_image', models.ImageField(upload_to='covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('ch_no', models.PositiveIntegerField(default=0)),
                ('summary', ckeditor.fields.RichTextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
