# Generated by Django 3.1.1 on 2020-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('want to read', 'want to read'), ('currently reading', 'currently reading'), ('completed', 'completed'), ('pause', 'pause')], default='currently reading', max_length=255),
        ),
    ]
