# Generated by Django 3.1.1 on 2020-09-29 15:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='chapters_read',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='my_review',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
